CREATE OR REPLACE PROCEDURE deleteIfNoCreditOrBalanceIsNull IS

BEGIN

    dbms_output.put_line('for debug purpose');
END;
/

BEGIN
    deleteIfNoCreditOrBalanceIsNull;
END;

---------

SELECT C1.ID, L.ID, (SUM(O2.AMOUNT_TRANSFER) - SUM(O3.AMOUNT_TRANSFER)) AS ACC_BALANCE
FROM CUSTOMER C1
    LEFT JOIN LOAN L ON C1.ID = L.ID_CUSTOMER
        FULL JOIN ACCOUNT ON C1.ID = ACCOUNT.ID_CUSTOMER
        FULL JOIN OPERATION O2 on ACCOUNT.ID = O2.ID_ACCOUNT_RECEIVER
                    FULL JOIN OPERATION O3 on ACCOUNT.ID = O3.ID_ACCOUNT_SENDER
WHERE L.ID IS NULL
GROUP BY C1.ID, L.ID
HAVING (SUM(O2.AMOUNT_TRANSFER) - SUM(O3.AMOUNT_TRANSFER)) = 0;

-------------------

DELETE
FROM CUSTOMER
WHERE CUSTOMER.ID IN (SELECT C1.ID, L.ID, (SUM(O2.AMOUNT_TRANSFER) - SUM(O3.AMOUNT_TRANSFER)) AS ACC_BALANCE
FROM CUSTOMER C1
    LEFT JOIN LOAN L ON C1.ID = L.ID_CUSTOMER
        FULL JOIN ACCOUNT ON C1.ID = ACCOUNT.ID_CUSTOMER
        FULL JOIN OPERATION O2 on ACCOUNT.ID = O2.ID_ACCOUNT_RECEIVER
                    FULL JOIN OPERATION O3 on ACCOUNT.ID = O3.ID_ACCOUNT_SENDER
WHERE L.ID IS NULL
GROUP BY C1.ID, L.ID
HAVING (SUM(O2.AMOUNT_TRANSFER) - SUM(O3.AMOUNT_TRANSFER)) = 0)


-------------
select user from dual