
CREATE PROFILE C##OPERATORS LIMIT
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LIFE_TIME 60
PASSWORD_REUSE_TIME 1800
PASSWORD_REUSE_MAX  50
PASSWORD_GRACE_TIME 10
PASSWORD_VERIFY_FUNCTION VERIFY_PASSWORD;

CREATE PROFILE C##CUSTOMERS LIMIT
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LIFE_TIME 60
PASSWORD_REUSE_TIME 1800
PASSWORD_REUSE_MAX  50
PASSWORD_GRACE_TIME 10
PASSWORD_VERIFY_FUNCTION VERIFY_PASSWORD;