INSERT INTO C##DIMA.MATHUSER (ID, USER_NAME, ID_USER) VALUES (1, 'C##DIMA', 1);
INSERT INTO C##DIMA.MATHUSER (ID, USER_NAME, ID_USER) VALUES (2, 'C##NEW_OPERATOR', 2);
INSERT INTO C##DIMA.MATHUSER (ID, USER_NAME, ID_USER) VALUES (3, 'C##NEW_OFFICIAL', 3);