CREATE TABLE OPERATION 
(
  ID NUMBER NOT NULL 
, ID_CUSTOMER NUMBER 
, DATE_OPERATION DATE 
, TYPE NUMBER 
, AMOUNT_TRANSFER NUMBER NOT NULL 
, ID_ACCOUNT_SENDER NUMBER NOT NULL 
, ID_ACCOUNT_RECEIVER NUMBER NOT NULL 
, CONSTRAINT OPERATION_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE OPERATION
ADD CONSTRAINT OPERATION_ACCOUNT_R_FK1 FOREIGN KEY
(
  ID_ACCOUNT_RECEIVER 
)
REFERENCES ACCOUNT
(
  ID 
)
ENABLE;

ALTER TABLE OPERATION
ADD CONSTRAINT OPERATION_ACCOUNT_S_FK1 FOREIGN KEY
(
  ID_ACCOUNT_SENDER 
)
REFERENCES ACCOUNT
(
  ID 
)
ENABLE;

ALTER TABLE OPERATION
ADD CONSTRAINT OPERATION_CUSTOMER_FK1 FOREIGN KEY
(
  ID_CUSTOMER 
)
REFERENCES CUSTOMER
(
  ID 
)
ENABLE;
