CREATE OR REPLACE TRIGGER trg_delete_from_reader
BEFORE DELETE
  on READER
  FOR EACH ROW 
BEGIN
-- Delete from PATIENT_DETAILS also
DELETE FROM EXTRADITION EX WHERE EX.ID_READER_EX = :OLD.ID_READER;
 
END;
/

DELETE FROM READER
WHERE EXISTS (SELECT *
                FROM extradition
                WHERE READER.ID_READER = EXTRADITION.ID_READER_EX AND (MONTHS_BETWEEN( TO_DATE ('01/10/2019', 'DD/MM/YYYY'), EXTRADITION.DATE_EXTRADITION )/12)>2);