SELECT C1.ID, O.ID_ACCOUNT_RECEIVER, O.ID_ACCOUNT_SENDER
    FROM CUSTOMER C1
         JOIN ACCOUNT A2 on C1.ID = A2.ID_CUSTOMER
            FULL JOIN OPERATION O on A2.ID = O.ID_ACCOUNT_RECEIVER
WHERE O.ID_ACCOUNT_RECEIVER IS NULL AND O.ID_ACCOUNT_SENDER IS NULL
GROUP BY C1.ID, O.ID_ACCOUNT_RECEIVER, O.ID_ACCOUNT_SENDER

--

SELECT A1.ID
FROM ACCOUNT A1
WHERE (A1.ID NOT IN (SELECT  O1.ID_ACCOUNT_SENDER FROM OPERATION O1)) AND (A1.ID NOT IN (SELECT  O1.ID_ACCOUNT_RECEIVER FROM OPERATION O1))
ORDER BY A1.ID;

------

SELECT C1.ID
FROM CUSTOMER C1
  FULL JOIN ACCOUNT A1
    ON A1.ID_CUSTOMER = C1.ID
WHERE A1.ID NOT IN (SELECT A1.ID
FROM ACCOUNT A1
WHERE A1.ID NOT IN (SELECT  O1.ID_ACCOUNT_SENDER FROM OPERATION O1)) AND (A1.ID NOT IN (SELECT  O1.ID_ACCOUNT_RECEIVER FROM OPERATION O1))
ORDER BY A1.ID;

----------

SELECT A1.ID, C1.ID
FROM ACCOUNT A1
  JOIN CUSTOMER C1
    ON C1.ID = A1.ID_CUSTOMER
WHERE (A1.ID NOT IN (SELECT  O1.ID_ACCOUNT_SENDER FROM OPERATION O1)) AND (A1.ID NOT IN (SELECT  O1.ID_ACCOUNT_RECEIVER FROM OPERATION O1))
ORDER BY A1.ID;