SELECT C1.ID, A1.ID
FROM CUSTOMER C1
  LEFT JOIN ACCOUNT A1
    ON A1.ID_CUSTOMER = C1.ID
WHERE A1.ID IS NULL;

------

SELECT A1.ID, O1.ID
FROM ACCOUNT A1
  LeFT JOIN OPERATION O1
    ON O1.ID_ACCOUNT_SENDER = A1.ID
WHERE O1.ID IS NULL;

----------------------------

SELECT A1.ID, O1.ID
FROM ACCOUNT A1
  LEFT JOIN OPERATION O1
    ON O1.ID_ACCOUNT_SENDER = A1.ID
       LEFT JOIN OPERATION O2
        ON O2.ID_ACCOUNT_RECEIVER = A1.ID
WHERE O1.ID IS NULL
ORDER BY A1.ID;


---------------------

SELECT A1.ID
FROM ACCOUNT A1
WHERE (A1.ID NOT IN (SELECT  O1.ID_ACCOUNT_SENDER FROM OPERATION O1)) AND (A1.ID NOT IN (SELECT  O1.ID_ACCOUNT_RECEIVER FROM OPERATION O1))
ORDER BY A1.ID;