--4.	Вывести данные о клиентах, имеющих льготы по кредиту и уменьшить этот кредит на 1%.
SELECT CUSTOMER.SECOND_NAME AS Имя, CUSTOMER.FIRST_NAME AS Имя, L.AMOUNT
FROM CUSTOMER
         JOIN DISCOUNT D on CUSTOMER.ID_DISCOUNT = D.ID
         JOIN LOAN L on CUSTOMER.ID = L.ID_CUSTOMER;

UPDATE
(SELECT L.AMOUNT
 FROM CUSTOMER
          JOIN DISCOUNT D on CUSTOMER.ID_DISCOUNT = D.ID
          JOIN LOAN L on CUSTOMER.ID = L.ID_CUSTOMER
) T
SET T.AMOUNT = T.AMOUNT - T.AMOUNT * 0.01;
