CREATE OR REPLACE
    TRIGGER ADT123
    AFTER INSERT OR DELETE OR UPDATE
    ON DEPARTMENT -- target table
DECLARE
BEGIN
    INSERT INTO "AUDIT"("USER_NAME",
                        "TIME")
    VALUES (USER, SYSDATE);
END ADT123;