INSERT INTO C##DIMA.DISCOUNT (ID, TITLE, AMOUNT) VALUES (3, 'Большая', 5);
INSERT INTO C##DIMA.DISCOUNT (ID, TITLE, AMOUNT) VALUES (2, 'Обычная', 2);
INSERT INTO C##DIMA.DISCOUNT (ID, TITLE, AMOUNT) VALUES (1, 'Малая', 1);