INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 3);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 4);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 7);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 10);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 14);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 16);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 19);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 22);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 25);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 28);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 31);
INSERT INTO OPERATION (ID, ID_CUSTOMER, DATE_OPERATION, TYPE, AMOUNT_TRANSFER, ID_ACCOUNT_SENDER, ID_ACCOUNT_RECEIVER)
VALUES (7, 12, TO_DATE(CURRENT_DATE), 0, 999, 9999, 34);